#!/bin/bash -e

# Eliminar la carpeta "externos" dentro de la carpeta distribuidora
cd distribuidora
cd extrernos
cd pendientes
rm lista.txt
cd ..
rmdir pendientes
rm lista.txt
cd ..
rmdir externos



