#!/bin/bash -e

# Eliminar la carpeta "externos" dentro de la carpeta distribuidora
cd distribuidora
cd extrernos
rmdir pendientes
rm lista.txt
rmdir tests
rm teste-remove-directory
cd ..
rmdir externos



